version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    ports: [3306:3306]
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
